variables:
  VERSION_ID: '1.0.$CI_PIPELINE_ID'

stages:
  - build

build:
  image: registry.gitlab.com/mc.dev/docker/electron-build-ci:latest
  stage: build
  only:
    - master

  artifacts:
    paths:
      - $CI_PROJECT_DIR/release/*.*
  script:
    - sed "s/0.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
    - npm i
    - npm run electron:windows
